name: rust-build
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
env:
  CARGO_TERM_COLOR: always
  STATIC_BUILD_TARGET: x86_64-unknown-linux-musl
jobs:
  check:
    strategy:
      matrix:
        os: [ macos-11, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./rust
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: cargo/build
        run: cargo build
      - name: cargo/test
        run: cargo test